2questao 
str_v = input("Qual é o seu nome? ")
#print(str_v)
print(type(str_v))
int_v = int(input("Quantos anos você tem? "))
#print(int_v)
print(type(int_v))
float_v = float(input("Digite um número decimal: "))
#print(float_v)
print(type(float_v))
bool_v = bool(input("O que significa false? "))
#print(bool_v)
print(type(bool_v))
