n1 = int(input("Escolha um número de 1 a 100: "))
n2 = int(input("Escolha um número de 1 a 100: "))
print("        ")
print(f"A soma desses números é: {n1+n2}")
print(f"A subtração desses números é: {n1-n2}")
print(f"O produto desses números é: {n1*n2}")
print(f"A divisão desses números é: {n1/n2}")
